class_name Sim

enum Res { FOOD, WOOD, STONE, IRON, STEEL, GEMS, ARCANA }
enum Race { HUMAN }
enum Cohort { CHILD, ADULT, ELDER }
enum ZoneType { FARM, MINE, LUMBER, SMELTER, HOUSING, BARRACKS, WORKSHOP, STOCKPILE }
